stages:
  - build-check
  - package
  - verify
  - cleanup

prepare-infra:
  stage: verify
  image: docker:24.0.5
  services: [docker:24.0.5-dind]
  script:
    - docker compose -f docker-compose.infra.yml up -d
  tags: [docker]

include:
  - local: 'auth-service/.gitlab-ci.yml'
  - local: 'companies-service/.gitlab-ci.yml'
  - local: 'bff-service/.gitlab-ci.yml'
  - local: 'logging-service/.gitlab-ci.yml'
  - local: 'kong/.gitlab-ci.yml'

stop-infra:
  stage: cleanup
  script:
    - docker compose -f docker-compose.infra.yml down
  when: always
