services:
  postgres-ci:
    image: postgres:18-alpine
    container_name: postgres-ci
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      LANG: en_US.utf8
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 5s
      retries: 5
    networks: [test-net]

  redis-ci:
    image: redis:7-alpine
    container_name: redis-ci
    command: ["redis-server", "--requirepass", "test"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "test", "PING"]
      interval: 5s
      retries: 5
    networks: [test-net]

  kafka-ci:
    image: apache/kafka:4.2.0
    container_name: kafka-ci
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-ci:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-ci:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks: [test-net]

networks:
  test-net:
    name: galaxy_test_net
    driver: bridge
