services:
  kong:
    image: kong/kong-gateway:3.14
    container_name: kong
    depends_on:
      - auth-service
      - companies-service
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_REQUIRE_HTTPS_OFF_TERMINATION: "yes"
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: info
      KONG_PLUGINS: "bundled,account-uuid-header"
    ports:
      - "8000:8000"
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
      - ./kong/plugins/account-uuid-header:/usr/local/share/lua/5.1/kong/plugins/account-uuid-header:ro
    restart: unless-stopped
    networks:
      - galaxy-net

  bff-service:
    build:
      context: ./bff-service
      dockerfile: Dockerfile
    container_name: bff-service
    environment:
      - GIN_MODE=release
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - COMPANIES_SERVICE_URL=${COMPANIES_SERVICE_URL}
    ports:
      - "8082:8082"
    depends_on:
      - auth-service
      - companies-service
    restart: unless-stopped
    networks:
      - galaxy-net

  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - pgdata-galaxy:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - galaxy-net

  postgres-logs:
    image: postgres:18-alpine
    container_name: postgres-logs
    environment:
      POSTGRES_USER: ${LOGS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LOGS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${LOGS_POSTGRES_DB}
    ports:
      - "5431:5432"
    volumes:
      - pgdata-galaxy-logs:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - galaxy-net

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: auth-service
    depends_on:
      auth-redis:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      REDIS_HOST: auth-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${AUTH_REDIS_PASSWORD}

      PASSWORD_HASHER_MEMORY_SIZE: ${PASSWORD_HASHER_MEMORY_SIZE}
      PASSWORD_HASHER_ITERATIONS: ${PASSWORD_HASHER_ITERATIONS}
      PASSWORD_HASHER_DEGREE_OF_PARALLELISM: ${PASSWORD_HASHER_DEGREE_OF_PARALLELISM}
      PASSWORD_HASHER_SALT_LENGTH: ${PASSWORD_HASHER_SALT_LENGTH}
      PASSWORD_HASHER_HASH_LENGTH: ${PASSWORD_HASHER_HASH_LENGTH}

      OTP_CODE_ACCESS_MINUTES: ${OTP_CODE_ACCESS_MINUTES}

      RESET_PASSWORD_TOKEN_ACCESS_MINUTES: ${RESET_PASSWORD_TOKEN_ACCESS_MINUTES}
    ports:
      - ":8080"
    restart: unless-stopped
    networks:
      - galaxy-net

  auth-redis:
    image: redis:7-alpine
    container_name: auth-redis
    command: ["redis-server", "--requirepass", "${AUTH_REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - auth_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${AUTH_REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - galaxy-net

  companies-service:
    build:
      context: ./companies-service
      dockerfile: Dockerfile
    container_name: companies-service
    environment:
      - GIN_MODE=release

      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

      - REDIS_HOST=companies-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${COMPANIES_REDIS_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      companies-redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - galaxy-net

  companies-redis:
    image: redis:7-alpine
    container_name: companies-redis
    command: ["redis-server", "--requirepass", "${COMPANIES_REDIS_PASSWORD}"]
    ports:
      - "6380:6379"
    volumes:
      - companies_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${COMPANIES_REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - galaxy-net


volumes:
  pgdata-galaxy:
  pgdata-galaxy-logs:
  auth_redis_data:
  companies_redis_data:

networks:
  galaxy-net:
