services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata-galaxy:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - galaxy-net

  postgres-logs:
    image: postgres:18-alpine
    container_name: postgres-logs
    environment:
      POSTGRES_USER: ${LOGS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LOGS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${LOGS_POSTGRES_DB}
    ports:
      - "${LOGS_POSTGRES_PORT}:5432"
    volumes:
      - pgdata-galaxy-logs:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - galaxy-net

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: auth-service
    depends_on:
      auth-redis:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      REDIS_HOST: auth-redis
    ports:
      - "${AUTH_PORT}:8080"
    restart: unless-stopped
    networks:
      - galaxy-net

  auth-redis:
    image: redis:7-alpine
    container_name: auth-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - galaxy-net

volumes:
  pgdata-galaxy:
  pgdata-galaxy-logs:
  redis_data:

networks:
  galaxy-net:
