services:
  redis-ci:
    image: redis:7-alpine
    container_name: redis-${SERVICE_NAME}
    env_file:
      - .env.ci
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 5s
      retries: 5
