services:
  minio-ci:
    image: minio/minio:latest
    container_name: minio-${SERVICE_NAME}
    env_file:
      - .env.ci
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
