variables:
  BFF_IMAGE: "$CI_REGISTRY_USER/bff-service:$CI_COMMIT_SHORT_SHA"

bff-compile:
  stage: build-check
  image: golang:1.25.7-alpine
  script:
    - cd bff-service
    - go mod download
    - go build -v -o /dev/null ./cmd/main.go
  rules:
    - changes:
        - bff-service/**/*

bff-docker-build:
  stage: package
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker build -t $BFF_IMAGE ./bff-service
    - docker push $BFF_IMAGE
  needs: ["bff-compile"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - bff-service/**/*

bff-health-check:
  stage: verify
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - docker run -d --name bff-test -p 8080:8080 $BFF_IMAGE
    - sleep 5
    - docker exec bff-test netstat -tuln | grep :8080 || (docker logs bff-test && exit 1)
    - docker exec bff-test wget --spider -q http://localhost:8080/health || (docker logs bff-test && exit 1)
  needs: ["bff-docker-build"]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - bff-service/**/*
