// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: companies.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO company.companies (company_uuid,
                               name,
                               description,
                               logo_file_id,
                               billing_status)
VALUES ($1, $2, $3, $4, $5)
RETURNING
    company_uuid,
    name,
    description,
    logo_file_id,
    billing_status
`

type CreateCompanyParams struct {
	CompanyUuid   string      `json:"company_uuid"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	LogoFileID    pgtype.Int4 `json:"logo_file_id"`
	BillingStatus string      `json:"billing_status"`
}

type CreateCompanyRow struct {
	CompanyUuid   string      `json:"company_uuid"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	LogoFileID    pgtype.Int4 `json:"logo_file_id"`
	BillingStatus string      `json:"billing_status"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (CreateCompanyRow, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.CompanyUuid,
		arg.Name,
		arg.Description,
		arg.LogoFileID,
		arg.BillingStatus,
	)
	var i CreateCompanyRow
	err := row.Scan(
		&i.CompanyUuid,
		&i.Name,
		&i.Description,
		&i.LogoFileID,
		&i.BillingStatus,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
UPDATE company.companies
SET is_active  = false,
    updated_at = NOW()
WHERE company_uuid = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, companyUuid string) error {
	_, err := q.db.Exec(ctx, deleteCompany, companyUuid)
	return err
}

const getCompanies = `-- name: GetCompanies :many
SELECT com.company_uuid,
       com.name,
       com.logo_file_id,
       com.billing_status,
       com.is_active
FROM company.companies com
         JOIN company.members mem ON com.company_uuid = mem.company_uuid
WHERE mem.account_uuid = $1
`

type GetCompaniesRow struct {
	CompanyUuid   string      `json:"company_uuid"`
	Name          string      `json:"name"`
	LogoFileID    pgtype.Int4 `json:"logo_file_id"`
	BillingStatus string      `json:"billing_status"`
	IsActive      bool        `json:"is_active"`
}

func (q *Queries) GetCompanies(ctx context.Context, accountUuid string) ([]GetCompaniesRow, error) {
	rows, err := q.db.Query(ctx, getCompanies, accountUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompaniesRow
	for rows.Next() {
		var i GetCompaniesRow
		if err := rows.Scan(
			&i.CompanyUuid,
			&i.Name,
			&i.LogoFileID,
			&i.BillingStatus,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompanyByUuid = `-- name: GetCompanyByUuid :one
SELECT com.company_uuid,
       com.name,
       com.description,
       com.logo_file_id,
       com.billing_status,
       com.billing_until,
       com.created_at,
       com.is_active
FROM company.companies com
         JOIN company.members mem ON com.company_uuid = mem.company_uuid AND
                                     mem.account_uuid = $1
WHERE com.company_uuid = $2
`

type GetCompanyByUuidParams struct {
	AccountUuid string `json:"account_uuid"`
	CompanyUuid string `json:"company_uuid"`
}

type GetCompanyByUuidRow struct {
	CompanyUuid   string             `json:"company_uuid"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	LogoFileID    pgtype.Int4        `json:"logo_file_id"`
	BillingStatus string             `json:"billing_status"`
	BillingUntil  pgtype.Timestamptz `json:"billing_until"`
	CreatedAt     time.Time          `json:"created_at"`
	IsActive      bool               `json:"is_active"`
}

func (q *Queries) GetCompanyByUuid(ctx context.Context, arg GetCompanyByUuidParams) (GetCompanyByUuidRow, error) {
	row := q.db.QueryRow(ctx, getCompanyByUuid, arg.AccountUuid, arg.CompanyUuid)
	var i GetCompanyByUuidRow
	err := row.Scan(
		&i.CompanyUuid,
		&i.Name,
		&i.Description,
		&i.LogoFileID,
		&i.BillingStatus,
		&i.BillingUntil,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const isCompanyOwner = `-- name: IsCompanyOwner :one
SELECT EXISTS (SELECT 1
               FROM company.members
               WHERE company_uuid = $1
                 AND account_uuid = $2
                 AND is_owner = TRUE
                 AND is_active = TRUE)
`

type IsCompanyOwnerParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
}

func (q *Queries) IsCompanyOwner(ctx context.Context, arg IsCompanyOwnerParams) (bool, error) {
	row := q.db.QueryRow(ctx, isCompanyOwner, arg.CompanyUuid, arg.AccountUuid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE company.companies
SET name         = COALESCE($2, name),
    description  = COALESCE($3, description),
    logo_file_id = COALESCE($4, logo_file_id),
    updated_at   = NOW()
WHERE company_uuid = $1
RETURNING
    company_uuid,
    name,
    description,
    logo_file_id,
    billing_status
`

type UpdateCompanyParams struct {
	CompanyUuid string      `json:"company_uuid"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoFileID  pgtype.Int4 `json:"logo_file_id"`
}

type UpdateCompanyRow struct {
	CompanyUuid   string      `json:"company_uuid"`
	Name          string      `json:"name"`
	Description   pgtype.Text `json:"description"`
	LogoFileID    pgtype.Int4 `json:"logo_file_id"`
	BillingStatus string      `json:"billing_status"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (UpdateCompanyRow, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.CompanyUuid,
		arg.Name,
		arg.Description,
		arg.LogoFileID,
	)
	var i UpdateCompanyRow
	err := row.Scan(
		&i.CompanyUuid,
		&i.Name,
		&i.Description,
		&i.LogoFileID,
		&i.BillingStatus,
	)
	return i, err
}
