// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package db

import (
	"context"
	"time"
)

const createMember = `-- name: CreateMember :exec
INSERT INTO company.members (company_uuid,
                             account_uuid,
                             role_id,
                             is_owner)
VALUES ($1, $2, $3, $4)
`

type CreateMemberParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
	RoleID      int32  `json:"role_id"`
	IsOwner     bool   `json:"is_owner"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) error {
	_, err := q.db.Exec(ctx, createMember,
		arg.CompanyUuid,
		arg.AccountUuid,
		arg.RoleID,
		arg.IsOwner,
	)
	return err
}

const deleteMember = `-- name: DeleteMember :exec
UPDATE company.members
SET is_active  = FALSE,
    updated_at = NOW()
WHERE company_uuid = $1
  AND account_uuid = $2
`

type DeleteMemberParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.CompanyUuid, arg.AccountUuid)
	return err
}

const getMembers = `-- name: GetMembers :many
SELECT m.account_uuid,
       m.role_id,
       m.created_at,
       r.name  AS role_name,
       r.color AS role_color
FROM company.members m
         JOIN company.roles r ON m.role_id = r.role_id
WHERE m.company_uuid = $1
ORDER BY m.created_at DESC
`

type GetMembersRow struct {
	AccountUuid string    `json:"account_uuid"`
	RoleID      int32     `json:"role_id"`
	CreatedAt   time.Time `json:"created_at"`
	RoleName    string    `json:"role_name"`
	RoleColor   string    `json:"role_color"`
}

func (q *Queries) GetMembers(ctx context.Context, companyUuid string) ([]GetMembersRow, error) {
	rows, err := q.db.Query(ctx, getMembers, companyUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersRow
	for rows.Next() {
		var i GetMembersRow
		if err := rows.Scan(
			&i.AccountUuid,
			&i.RoleID,
			&i.CreatedAt,
			&i.RoleName,
			&i.RoleColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembersStatuses = `-- name: GetMembersStatuses :many
SELECT account_uuid, is_owner
FROM company.members
WHERE company_uuid = $1
  AND account_uuid IN ($2, $3)
`

type GetMembersStatusesParams struct {
	CompanyUuid   string `json:"company_uuid"`
	AccountUuid   string `json:"account_uuid"`
	AccountUuid_2 string `json:"account_uuid_2"`
}

type GetMembersStatusesRow struct {
	AccountUuid string `json:"account_uuid"`
	IsOwner     bool   `json:"is_owner"`
}

func (q *Queries) GetMembersStatuses(ctx context.Context, arg GetMembersStatusesParams) ([]GetMembersStatusesRow, error) {
	rows, err := q.db.Query(ctx, getMembersStatuses, arg.CompanyUuid, arg.AccountUuid, arg.AccountUuid_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersStatusesRow
	for rows.Next() {
		var i GetMembersStatusesRow
		if err := rows.Scan(&i.AccountUuid, &i.IsOwner); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOwner = `-- name: SetOwner :execrows
UPDATE company.members
SET is_owner   = TRUE,
    updated_at = NOW()
WHERE company_uuid = $1
  AND account_uuid = $2
`

type SetOwnerParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
}

func (q *Queries) SetOwner(ctx context.Context, arg SetOwnerParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOwner, arg.CompanyUuid, arg.AccountUuid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRoleMember = `-- name: UpdateRoleMember :execrows
UPDATE company.members
SET role_id = $3
WHERE company_uuid = $1
  AND account_uuid = $2
`

type UpdateRoleMemberParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
	RoleID      int32  `json:"role_id"`
}

func (q *Queries) UpdateRoleMember(ctx context.Context, arg UpdateRoleMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRoleMember, arg.CompanyUuid, arg.AccountUuid, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
