// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CompanyCompany struct {
	CompanyUuid   string             `json:"company_uuid"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	LogoFileID    pgtype.Int4        `json:"logo_file_id"`
	BillingStatus string             `json:"billing_status"`
	BillingUntil  pgtype.Timestamptz `json:"billing_until"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	IsActive      bool               `json:"is_active"`
}

type CompanyMember struct {
	CompanyUuid string    `json:"company_uuid"`
	AccountUuid string    `json:"account_uuid"`
	RoleID      int32     `json:"role_id"`
	IsOwner     bool      `json:"is_owner"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	IsActive    bool      `json:"is_active"`
}

type CompanyOutboxEvent struct {
	MessageUuid string             `json:"message_uuid"`
	AccountUuid string             `json:"account_uuid"`
	RequestID   string             `json:"request_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	RetryCount  int32              `json:"retry_count"`
	LastError   pgtype.Text        `json:"last_error"`
	CreatedAt   time.Time          `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

type CompanyPermission struct {
	CompanyUuid string    `json:"company_uuid"`
	AccountUuid string    `json:"account_uuid"`
	Domain      string    `json:"domain"`
	Mask        int64     `json:"mask"`
	ChangeBy    string    `json:"change_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	IsActive    bool      `json:"is_active"`
}

type CompanyPlan struct {
	PlanID      int32          `json:"plan_id"`
	Name        string         `json:"name"`
	Description string         `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Period      int32          `json:"period"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	IsActive    bool           `json:"is_active"`
}

type CompanyRole struct {
	RoleID      int32       `json:"role_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       string      `json:"color"`
	CompanyUuid string      `json:"company_uuid"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	IsActive    bool        `json:"is_active"`
}
