// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"
)

const deleteAllPermissionsCompany = `-- name: DeleteAllPermissionsCompany :many
WITH updated_rows AS (
    UPDATE company.permissions
    SET is_active  = false,
        updated_at = now(),
        change_by  = $2
    WHERE company_uuid = $1
    RETURNING account_uuid
)
SELECT DISTINCT account_uuid FROM updated_rows
`

type DeleteAllPermissionsCompanyParams struct {
	CompanyUuid string `json:"company_uuid"`
	ChangeBy    string `json:"change_by"`
}

func (q *Queries) DeleteAllPermissionsCompany(ctx context.Context, arg DeleteAllPermissionsCompanyParams) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteAllPermissionsCompany, arg.CompanyUuid, arg.ChangeBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var account_uuid string
		if err := rows.Scan(&account_uuid); err != nil {
			return nil, err
		}
		items = append(items, account_uuid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllPermissionsMember = `-- name: DeleteAllPermissionsMember :exec
UPDATE company.permissions
SET is_active  = false,
    updated_at = now(),
    change_by  = $3
WHERE company_uuid = $1
  AND account_uuid = $2
`

type DeleteAllPermissionsMemberParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
	ChangeBy    string `json:"change_by"`
}

func (q *Queries) DeleteAllPermissionsMember(ctx context.Context, arg DeleteAllPermissionsMemberParams) error {
	_, err := q.db.Exec(ctx, deleteAllPermissionsMember, arg.CompanyUuid, arg.AccountUuid, arg.ChangeBy)
	return err
}

const getUserAllPermissions = `-- name: GetUserAllPermissions :many
SELECT domain,
       mask
FROM company.permissions
WHERE company_uuid = $1
  AND account_uuid = $2
`

type GetUserAllPermissionsParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
}

type GetUserAllPermissionsRow struct {
	Domain string `json:"domain"`
	Mask   int64  `json:"mask"`
}

func (q *Queries) GetUserAllPermissions(ctx context.Context, arg GetUserAllPermissionsParams) ([]GetUserAllPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserAllPermissions, arg.CompanyUuid, arg.AccountUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAllPermissionsRow
	for rows.Next() {
		var i GetUserAllPermissionsRow
		if err := rows.Scan(&i.Domain, &i.Mask); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissionMask = `-- name: GetUserPermissionMask :one
SELECT mask, is_active
FROM company.permissions
WHERE company_uuid = $1
  AND account_uuid = $2
  AND domain = $3
  AND is_active = true
`

type GetUserPermissionMaskParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
	Domain      string `json:"domain"`
}

type GetUserPermissionMaskRow struct {
	Mask     int64 `json:"mask"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) GetUserPermissionMask(ctx context.Context, arg GetUserPermissionMaskParams) (GetUserPermissionMaskRow, error) {
	row := q.db.QueryRow(ctx, getUserPermissionMask, arg.CompanyUuid, arg.AccountUuid, arg.Domain)
	var i GetUserPermissionMaskRow
	err := row.Scan(&i.Mask, &i.IsActive)
	return i, err
}

const giveAccess = `-- name: GiveAccess :exec
INSERT INTO company.permissions (company_uuid,
                                 account_uuid,
                                 domain,
                                 mask,
                                 change_by)
VALUES ($1, $2, $3, $4, $5)
`

type GiveAccessParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
	Domain      string `json:"domain"`
	Mask        int64  `json:"mask"`
	ChangeBy    string `json:"change_by"`
}

func (q *Queries) GiveAccess(ctx context.Context, arg GiveAccessParams) error {
	_, err := q.db.Exec(ctx, giveAccess,
		arg.CompanyUuid,
		arg.AccountUuid,
		arg.Domain,
		arg.Mask,
		arg.ChangeBy,
	)
	return err
}

const updatePermissions = `-- name: UpdatePermissions :exec
INSERT INTO company.permissions (company_uuid,
                                 account_uuid,
                                 domain,
                                 mask,
                                 change_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (company_uuid, account_uuid, domain)
    DO UPDATE SET mask       = EXCLUDED.mask,
                  change_by  = EXCLUDED.change_by,
                  updated_at = NOW()
`

type UpdatePermissionsParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
	Domain      string `json:"domain"`
	Mask        int64  `json:"mask"`
	ChangeBy    string `json:"change_by"`
}

func (q *Queries) UpdatePermissions(ctx context.Context, arg UpdatePermissionsParams) error {
	_, err := q.db.Exec(ctx, updatePermissions,
		arg.CompanyUuid,
		arg.AccountUuid,
		arg.Domain,
		arg.Mask,
		arg.ChangeBy,
	)
	return err
}
