// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"
)

const getUserAllPermissions = `-- name: GetUserAllPermissions :many
SELECT
    domain,
    mask
FROM company.permissions
WHERE company_uuid = $1 AND
      account_uuid = $2
`

type GetUserAllPermissionsParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
}

type GetUserAllPermissionsRow struct {
	Domain string `json:"domain"`
	Mask   int64  `json:"mask"`
}

func (q *Queries) GetUserAllPermissions(ctx context.Context, arg GetUserAllPermissionsParams) ([]GetUserAllPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserAllPermissions, arg.CompanyUuid, arg.AccountUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAllPermissionsRow
	for rows.Next() {
		var i GetUserAllPermissionsRow
		if err := rows.Scan(&i.Domain, &i.Mask); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissionMask = `-- name: GetUserPermissionMask :one
SELECT mask, is_active
FROM company.permissions
WHERE company_uuid = $1
  AND account_uuid = $2
  AND domain = $3
  AND is_active = true
`

type GetUserPermissionMaskParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
	Domain      string `json:"domain"`
}

type GetUserPermissionMaskRow struct {
	Mask     int64 `json:"mask"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) GetUserPermissionMask(ctx context.Context, arg GetUserPermissionMaskParams) (GetUserPermissionMaskRow, error) {
	row := q.db.QueryRow(ctx, getUserPermissionMask, arg.CompanyUuid, arg.AccountUuid, arg.Domain)
	var i GetUserPermissionMaskRow
	err := row.Scan(&i.Mask, &i.IsActive)
	return i, err
}

const giveAccess = `-- name: GiveAccess :exec
INSERT INTO company.permissions (company_uuid,
                                 account_uuid,
                                 domain,
                                 mask,
                                 change_by)
VALUES ($1, $2, $3, $4, $5)
`

type GiveAccessParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
	Domain      string `json:"domain"`
	Mask        int64  `json:"mask"`
	ChangeBy    string `json:"change_by"`
}

func (q *Queries) GiveAccess(ctx context.Context, arg GiveAccessParams) error {
	_, err := q.db.Exec(ctx, giveAccess,
		arg.CompanyUuid,
		arg.AccountUuid,
		arg.Domain,
		arg.Mask,
		arg.ChangeBy,
	)
	return err
}

const updatePermissions = `-- name: UpdatePermissions :exec
INSERT INTO company.permissions (
    company_uuid,
    account_uuid,
    domain,
    mask,
    change_by
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (company_uuid, account_uuid, domain)
DO UPDATE SET
    mask = EXCLUDED.mask,
    change_by = EXCLUDED.change_by,
    updated_at = NOW()
`

type UpdatePermissionsParams struct {
	CompanyUuid string `json:"company_uuid"`
	AccountUuid string `json:"account_uuid"`
	Domain      string `json:"domain"`
	Mask        int64  `json:"mask"`
	ChangeBy    string `json:"change_by"`
}

func (q *Queries) UpdatePermissions(ctx context.Context, arg UpdatePermissionsParams) error {
	_, err := q.db.Exec(ctx, updatePermissions,
		arg.CompanyUuid,
		arg.AccountUuid,
		arg.Domain,
		arg.Mask,
		arg.ChangeBy,
	)
	return err
}
