// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO company.roles (name, description, color, company_uuid)
VALUES ($1, $2, $3, $4)
RETURNING
    role_id,
    name,
    description,
    color,
    created_at,
    is_active
`

type CreateRoleParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       string      `json:"color"`
	CompanyUuid string      `json:"company_uuid"`
}

type CreateRoleRow struct {
	RoleID      int32       `json:"role_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       string      `json:"color"`
	CreatedAt   time.Time   `json:"created_at"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.CompanyUuid,
	)
	var i CreateRoleRow
	err := row.Scan(
		&i.RoleID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
UPDATE company.roles
SET is_active  = false,
    updated_at = NOW()
WHERE company_uuid = $1
  AND role_id = $2
`

type DeleteRoleParams struct {
	CompanyUuid string `json:"company_uuid"`
	RoleID      int32  `json:"role_id"`
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.Exec(ctx, deleteRole, arg.CompanyUuid, arg.RoleID)
	return err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT role_id
FROM company.roles
WHERE company_uuid = $1
  AND name = $2
`

type GetRoleByNameParams struct {
	CompanyUuid string `json:"company_uuid"`
	Name        string `json:"name"`
}

func (q *Queries) GetRoleByName(ctx context.Context, arg GetRoleByNameParams) (int32, error) {
	row := q.db.QueryRow(ctx, getRoleByName, arg.CompanyUuid, arg.Name)
	var role_id int32
	err := row.Scan(&role_id)
	return role_id, err
}

const getRoleByUuid = `-- name: GetRoleByUuid :one
SELECT role_id,
       name,
       description,
       color,
       created_at,
       is_active
FROM company.roles
WHERE company_uuid = $1
  AND role_id = $2
`

type GetRoleByUuidParams struct {
	CompanyUuid string `json:"company_uuid"`
	RoleID      int32  `json:"role_id"`
}

type GetRoleByUuidRow struct {
	RoleID      int32       `json:"role_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       string      `json:"color"`
	CreatedAt   time.Time   `json:"created_at"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) GetRoleByUuid(ctx context.Context, arg GetRoleByUuidParams) (GetRoleByUuidRow, error) {
	row := q.db.QueryRow(ctx, getRoleByUuid, arg.CompanyUuid, arg.RoleID)
	var i GetRoleByUuidRow
	err := row.Scan(
		&i.RoleID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT role_id,
       name,
       color,
       is_active
FROM company.roles
WHERE company_uuid = $1
`

type GetRolesRow struct {
	RoleID   int32  `json:"role_id"`
	Name     string `json:"name"`
	Color    string `json:"color"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) GetRoles(ctx context.Context, companyUuid string) ([]GetRolesRow, error) {
	rows, err := q.db.Query(ctx, getRoles, companyUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRolesRow
	for rows.Next() {
		var i GetRolesRow
		if err := rows.Scan(
			&i.RoleID,
			&i.Name,
			&i.Color,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isExistsRole = `-- name: IsExistsRole :one
SELECT count(*) != 0
FROM company.roles
WHERE company_uuid = $1
  AND name = $2
`

type IsExistsRoleParams struct {
	CompanyUuid string `json:"company_uuid"`
	Name        string `json:"name"`
}

func (q *Queries) IsExistsRole(ctx context.Context, arg IsExistsRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, isExistsRole, arg.CompanyUuid, arg.Name)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE company.roles
SET name        = COALESCE($3, name),
    description = COALESCE($4, description),
    color       = COALESCE($5, color),
    updated_at  = NOW()
WHERE company_uuid = $1
  AND role_id = $2
RETURNING
    role_id,
    name,
    description,
    color,
    created_at,
    is_active
`

type UpdateRoleParams struct {
	CompanyUuid string      `json:"company_uuid"`
	RoleID      int32       `json:"role_id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       pgtype.Text `json:"color"`
}

type UpdateRoleRow struct {
	RoleID      int32       `json:"role_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       string      `json:"color"`
	CreatedAt   time.Time   `json:"created_at"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (UpdateRoleRow, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.CompanyUuid,
		arg.RoleID,
		arg.Name,
		arg.Description,
		arg.Color,
	)
	var i UpdateRoleRow
	err := row.Scan(
		&i.RoleID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.CreatedAt,
		&i.IsActive,
	)
	return i, err
}
