// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO file.files (entity_type,
                        entity_id,
                        name,
                        size,
                        content_type,
                        storage_key,
                        created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING file_id, created_at
`

type CreateFileParams struct {
	EntityType  string      `json:"entity_type"`
	EntityID    pgtype.Text `json:"entity_id"`
	Name        string      `json:"name"`
	Size        int64       `json:"size"`
	ContentType string      `json:"content_type"`
	StorageKey  string      `json:"storage_key"`
	CreatedBy   string      `json:"created_by"`
}

type CreateFileRow struct {
	FileID    int64     `json:"file_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (CreateFileRow, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.EntityType,
		arg.EntityID,
		arg.Name,
		arg.Size,
		arg.ContentType,
		arg.StorageKey,
		arg.CreatedBy,
	)
	var i CreateFileRow
	err := row.Scan(&i.FileID, &i.CreatedAt)
	return i, err
}

const deleteAllFilesEntity = `-- name: DeleteAllFilesEntity :many
UPDATE file.files
SET is_active  = FALSE,
    status = 'DELETED',
    updated_at = now()
WHERE entity_id = $1
RETURNING storage_key
`

func (q *Queries) DeleteAllFilesEntity(ctx context.Context, entityID pgtype.Text) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteAllFilesEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteFile = `-- name: DeleteFile :one
UPDATE file.files
SET is_active  = FALSE,
    status = 'DELETED',
    updated_at = now()
WHERE file_id = $1
  AND entity_id = $2
RETURNING storage_key
`

type DeleteFileParams struct {
	FileID   int64       `json:"file_id"`
	EntityID pgtype.Text `json:"entity_id"`
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteFile, arg.FileID, arg.EntityID)
	var storage_key string
	err := row.Scan(&storage_key)
	return storage_key, err
}

const getFileById = `-- name: GetFileById :one
SELECT name,
       size,
       content_type,
       storage_key
FROM file.files
WHERE file_id = $1
`

type GetFileByIdRow struct {
	Name        string `json:"name"`
	Size        int64  `json:"size"`
	ContentType string `json:"content_type"`
	StorageKey  string `json:"storage_key"`
}

func (q *Queries) GetFileById(ctx context.Context, fileID int64) (GetFileByIdRow, error) {
	row := q.db.QueryRow(ctx, getFileById, fileID)
	var i GetFileByIdRow
	err := row.Scan(
		&i.Name,
		&i.Size,
		&i.ContentType,
		&i.StorageKey,
	)
	return i, err
}

const getFiles = `-- name: GetFiles :many
SELECT file_id,
       entity_type,
       entity_id,
       name,
       size,
       content_type,
       storage_key,
       status,
       created_by,
       created_at,
       is_active
FROM file.files
WHERE file_id = ANY($1::bigint[])
  AND entity_id = $2
`

type GetFilesParams struct {
	Column1  []int64     `json:"column_1"`
	EntityID pgtype.Text `json:"entity_id"`
}

type GetFilesRow struct {
	FileID      int64       `json:"file_id"`
	EntityType  string      `json:"entity_type"`
	EntityID    pgtype.Text `json:"entity_id"`
	Name        string      `json:"name"`
	Size        int64       `json:"size"`
	ContentType string      `json:"content_type"`
	StorageKey  string      `json:"storage_key"`
	Status      string      `json:"status"`
	CreatedBy   string      `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) GetFiles(ctx context.Context, arg GetFilesParams) ([]GetFilesRow, error) {
	rows, err := q.db.Query(ctx, getFiles, arg.Column1, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilesRow
	for rows.Next() {
		var i GetFilesRow
		if err := rows.Scan(
			&i.FileID,
			&i.EntityType,
			&i.EntityID,
			&i.Name,
			&i.Size,
			&i.ContentType,
			&i.StorageKey,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFileAsProcessed = `-- name: MarkFileAsProcessed :execrows
UPDATE file.files
SET status = 'PROCESSED',
    entity_id = $2,
    updated_at = now()
WHERE file_id = $1
  AND entity_id IS NULL
`

type MarkFileAsProcessedParams struct {
	FileID   int64       `json:"file_id"`
	EntityID pgtype.Text `json:"entity_id"`
}

func (q *Queries) MarkFileAsProcessed(ctx context.Context, arg MarkFileAsProcessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFileAsProcessed, arg.FileID, arg.EntityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
