// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type FileFile struct {
	FileID      int64       `json:"file_id"`
	EntityType  string      `json:"entity_type"`
	EntityID    pgtype.Text `json:"entity_id"`
	Name        string      `json:"name"`
	Size        int64       `json:"size"`
	ContentType string      `json:"content_type"`
	StorageKey  string      `json:"storage_key"`
	Status      string      `json:"status"`
	CreatedBy   string      `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	IsActive    bool        `json:"is_active"`
}

type FileOutboxEvent struct {
	MessageUuid string             `json:"message_uuid"`
	AccountUuid string             `json:"account_uuid"`
	RequestID   string             `json:"request_id"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	RetryCount  int32              `json:"retry_count"`
	LastError   pgtype.Text        `json:"last_error"`
	CreatedAt   time.Time          `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}
