// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outboxEvents.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :exec
INSERT INTO file.outbox_events (message_uuid,
                                   account_uuid,
                                   request_id,
                                   event_type,
                                   payload)
VALUES ($1, $2, $3, $4, $5)
`

type CreateOutboxEventParams struct {
	MessageUuid string `json:"message_uuid"`
	AccountUuid string `json:"account_uuid"`
	RequestID   string `json:"request_id"`
	EventType   string `json:"event_type"`
	Payload     []byte `json:"payload"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error {
	_, err := q.db.Exec(ctx, createOutboxEvent,
		arg.MessageUuid,
		arg.AccountUuid,
		arg.RequestID,
		arg.EventType,
		arg.Payload,
	)
	return err
}

const getUnprocessedEvents = `-- name: GetUnprocessedEvents :many
SELECT message_uuid,
       account_uuid,
       event_type,
       payload,
       status,
       retry_count,
       last_error,
       created_at,
       processed_at,
       locked_until
FROM file.outbox_events
WHERE status = 'PENDING'
ORDER BY created_at ASC
LIMIT 50
`

type GetUnprocessedEventsRow struct {
	MessageUuid string             `json:"message_uuid"`
	AccountUuid string             `json:"account_uuid"`
	EventType   string             `json:"event_type"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	RetryCount  int32              `json:"retry_count"`
	LastError   pgtype.Text        `json:"last_error"`
	CreatedAt   time.Time          `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) GetUnprocessedEvents(ctx context.Context) ([]GetUnprocessedEventsRow, error) {
	rows, err := q.db.Query(ctx, getUnprocessedEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnprocessedEventsRow
	for rows.Next() {
		var i GetUnprocessedEventsRow
		if err := rows.Scan(
			&i.MessageUuid,
			&i.AccountUuid,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.LastError,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventFailed = `-- name: MarkEventFailed :exec
UPDATE file.outbox_events
SET retry_count = retry_count + 1,
    last_error  = $2
WHERE message_uuid = $1
`

type MarkEventFailedParams struct {
	MessageUuid string      `json:"message_uuid"`
	LastError   pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkEventFailed(ctx context.Context, arg MarkEventFailedParams) error {
	_, err := q.db.Exec(ctx, markEventFailed, arg.MessageUuid, arg.LastError)
	return err
}

const markEventProcessed = `-- name: MarkEventProcessed :exec
UPDATE file.outbox_events
SET status       = 'PROCESSED',
    processed_at = NOW()
WHERE message_uuid = $1
`

func (q *Queries) MarkEventProcessed(ctx context.Context, messageUuid string) error {
	_, err := q.db.Exec(ctx, markEventProcessed, messageUuid)
	return err
}
