// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (CreateFileRow, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) error
	DeleteAllFilesEntity(ctx context.Context, entityID pgtype.Text) ([]string, error)
	DeleteFile(ctx context.Context, arg DeleteFileParams) (string, error)
	GetFileById(ctx context.Context, fileID int64) (GetFileByIdRow, error)
	GetFiles(ctx context.Context, arg GetFilesParams) ([]GetFilesRow, error)
	GetUnprocessedEvents(ctx context.Context) ([]GetUnprocessedEventsRow, error)
	MarkEventFailed(ctx context.Context, arg MarkEventFailedParams) error
	MarkEventProcessed(ctx context.Context, messageUuid string) error
	MarkFileAsProcessed(ctx context.Context, arg MarkFileAsProcessedParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
