variables:
  KONG_IMAGE: "kong/kong-gateway:3.14"

kong-validate-config:
  stage: build-check
  image: kong/kong-gateway:3.14
  script:
    - cp ./kong/kong.yml /tmp/kong.yml
    - kong config parse /tmp/kong.yml
  rules:
    - changes:
        - kong/**/*

kong-verify:
  stage: verify
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - >
      docker run -d --name kong-test
      -v $(pwd)/kong/kong.yml:/etc/kong/kong.yml
      -v $(pwd)/kong/plugins/account-uuid-header:/usr/local/share/lua/5.1/kong/plugins/account-uuid-header
      -e "KONG_DATABASE=off"
      -e "KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml"
      -e "KONG_PLUGINS=bundled,account-uuid-header"
      $KONG_IMAGE
    - sleep 5
    - docker exec kong-test kong health
  needs: ["kong-validate-config"]
  rules:
    - changes:
        - kong/**/*
